// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrategyOps.Kpi.Api.Infrastructure;

#nullable disable

namespace StrategyOps.Kpi.Api.Infrastructure.Migrations
{
    [DbContext(typeof(KpiDbContext))]
    [Migration("20260831014150_InitialKpiSchema")]
    partial class InitialKpiSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("StrategyOps.BuildingBlocks.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("StrategyOps.BuildingBlocks.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProcessedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProcessedAtUtc", "Sequence")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("StrategyOps.Kpi.Api.Domain.KpiDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmberThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LatestPeriodEndUtc")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LatestValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScorecardId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Target")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScorecardId");

                    b.ToTable("kpis", (string)null);
                });

            modelBuilder.Entity("StrategyOps.Kpi.Api.Domain.KpiMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KpiId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PeriodEndUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KpiId", "PeriodEndUtc");

                    b.ToTable("measurements", (string)null);
                });

            modelBuilder.Entity("StrategyOps.Kpi.Api.Domain.KpiScorecard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("scorecards", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
