<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\StrategyOps.BuildingBlocks\StrategyOps.BuildingBlocks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="StrategyOps.Domain.Tests" />
    <InternalsVisibleTo Include="StrategyOps.Slice.Tests" />
    <InternalsVisibleTo Include="StrategyOps.Messaging.Tests" />
  </ItemGroup>

</Project>
