// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrategyOps.Reporting.Api.Infrastructure;

#nullable disable

namespace StrategyOps.Reporting.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("StrategyOps.BuildingBlocks.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("StrategyOps.Reporting.Api.Domain.PortfolioScorecard", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BenefitForecast")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BenefitRealised")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("BenefitStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CriticalOpenIssues")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriticalOpenRisks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EscalatedRisks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("KpiAmber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KpiGreen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KpiNotMeasured")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KpiRed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KpiTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenIssues")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenRisks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RealisationPercent")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectCode");

                    b.HasIndex("Stage");

                    b.ToTable("portfolio_scorecards", (string)null);
                });

            modelBuilder.Entity("StrategyOps.Reporting.Api.Domain.ProjectKpiStatus", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KpiId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "KpiId");

                    b.ToTable("project_kpi_statuses", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
