// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrategyOps.Risk.Api.Infrastructure;

#nullable disable

namespace StrategyOps.Risk.Api.Infrastructure.Migrations
{
    [DbContext(typeof(RiskDbContext))]
    [Migration("20260831012519_InitialRiskSchema")]
    partial class InitialRiskSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("StrategyOps.BuildingBlocks.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("StrategyOps.BuildingBlocks.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProcessedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProcessedAtUtc", "Sequence")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("StrategyOps.Risk.Api.Domain.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EscalatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EscalationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Impact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MitigationPlan")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Probability")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RaisedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RegisterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegisterId");

                    b.HasIndex("RegisterId", "Status");

                    b.ToTable("risks", (string)null);
                });

            modelBuilder.Entity("StrategyOps.Risk.Api.Domain.RiskRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("risk_registers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
